# http://192.168.64.6:30997/   (NOT HTTPS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deployment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deployment-app
  template:
    metadata:
      labels:
        app: my-deployment-app
    spec:
      containers:
      - image: nbrown/nginxhello
        name: nginxhello
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: my-deployment-service
  labels:
    app: my-deployment-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30997
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deployment-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---