apiVersion: v1
kind: Service
metadata:
  name: node-express-api
  labels:
    app: node-express-api
spec:
  selector:
    app: node-express-api
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30001
  type: LoadBalancer